//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selfhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Digital : Game
    {
        public string GameKey { get; set; }
        public string Platform { get; set; }
    }
}
