//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selfhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderNumber { get; set; }
        public string CustomerName { get; set; }
        public int ItemID { get; set; }
        public int ItemCount { get; set; }
        public decimal PriceATOP { get; set; }
        public System.DateTime OrderTimestamp { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
